CREATE DATABASE atvGC;
-- USE atvGC;

-- Cria a tabela produto com codificação UTF-8 para permitir caracteres especiais
CREATE TABLE produto (
    preco NUMERIC(38,2),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255)
);